#!/usr/bin/env bash
# Install and configure HAProxy load balancer

# Install haproxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy with roundrobin and servers web-01, web-02
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << "EOF"
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 35.174.213.254:80 check
    server web-02 100.25.149.10:80 check
EOF'

# Restart HAProxy
sudo service haproxy restart
