#!/usr/bin/env bash
# Sets up HAProxy on a new Ubuntu machine with round-robin load balancing

# Update and install HAProxy
apt-get update -y
apt-get install haproxy -y

# Enable HAProxy to start on boot
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 256

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 <WEB_01_PRIVATE_IP>:80 check
    server web-02 <WEB_02_PRIVATE_IP>:80 check
EOF

# Restart HAProxy to apply changes
systemctl restart haproxy
